# Generated by Django 5.2 on 2025-04-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="place",
            field=models.CharField(
                help_text="Укажите место, где вы будете заниматься привычкой", max_length=100, verbose_name="Место"
            ),
        ),
    ]
