name: Django CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Flake8
        run: flake8 .

  test:
    needs: lint
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      NAME: ${{ secrets.NAME}}

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-    

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: python manage.py test

  build:
    needs: test
    runs-on: ubuntu-latest
    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}


    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          touch .env
          echo '"${{ secrets.SECRET_KEY }}"' | sed "s/\"//g" > .env

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Build and Push Docker images with Docker Compose
        run: |
            docker-compose build
            docker-compose push

#      - name: Build Docker image
#        run: docker build
#
#      - name: Push Docker image to Docker Hub
#        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/habits:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      SSH_KEY: ${{ secrets.SSH_KEY }}
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SERVER_IP: ${{ secrets.SERVER_IP }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEPLOY_DIR: ${{ secrets.DEPLOY_DIR }}

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

#      - name: Add server to known_hosts
#        run: |
#            ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          ssh -l test -p22 51.250.41.177 << EOF2
          docker-compose down || { echo "docker-compose down failed"; exit 1; }
          docker-compose pull || { echo "docker-compose pull failed"; exit 1; }
          docker-compose push ${{ secrets.DOCKER_HUB_USERNAME }}/habits:${{ github.sha }}
          docker-compose up -d --build || { echo "docker-compose up failed"; exit 1; }
          EOF2
          EOF

#      - name: Deploy to Server
#        run: |
#            ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << EOF
#              ssh -l test -p22 51.250.41.177 << EOF2
#              docker-compose down
#              docker-compose pull
#              docker-compose push ${{ secrets.DOCKER_HUB_USERNAME }}/habits:${{ github.sha }}
#              docker-compose up -d --build
##                docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/habits:${{ github.sha }}
##                docker stop habits || true
##                docker rm habits || true
##                docker run -d --name habits -p 80:8000 ${{ secrets.DOCKER_HUB_USERNAME }}/habits:${{ github.sha }}
#              EOF2
#            EOF

      - name: Check running containers
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "docker ps"
#      - name: Add server to known_hosts
#        run: |
#            ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
#
#      - name: Generate .env file
#        run: |
#          echo "SSH_KEY: ${{ secrets.SSH_KEY }}" > .env
#          echo "DEBUG=False" >> .env
#          echo "SSH_USER: ${{ secrets.SSH_USER }}" >> .env
#          echo "SERVER_IP: ${{ secrets.SERVER_IP }}" >> .env
#          echo "SECRET_KEY: django-insecure-#b7%9!4l5$49-^05xk8bjtuvew1&yphe7wl&9dwl8_gwdfe70+" >> .env
#          echo "DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}" >> .env
#          echo "DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" >> .env
#          cat .env
#
#      - name: Copy project files to server
#        run: |
#          rsync -avz --exclude '__pycache__' --exclude 'venv' --exclude '.git' . \
#            ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:habits
#
#      - name: Upload .env to server
#        run: |
#          rsync -avz .env ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:habits/.env
#
#      - name: Install Docker and Docker Compose on server (if not installed)
#        run: |
#          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
#            set -e
#            if ! command -v docker &> /dev/null; then
#              echo "Docker not found. Installing..."
#              curl -fsSL https://get.docker.com | sudo sh
#              sudo usermod -aG docker $USER
#              newgrp docker
#            else
#              echo "Docker already installed."
#            fi
#
#            if ! command -v docker-compose &> /dev/null; then
#              echo "Installing Docker Compose..."
#              sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
#              sudo chmod +x /usr/local/bin/docker-compose
#            else
#              echo "Docker Compose already installed."
#            fi
#          EOF

#      - name: Wait for backend container to be ready
#        run: |
#          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
#            set -e
#            until curl -S http:// ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}; do
#              echo "Waiting for backend to be ready..."
#              sleep 5
#            done
#            echo "Backend is ready."
#          EOF

#      - name: Restart docker-compose on server
#        run: |
#          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
#            set -e
#            cd habits
#            echo "Stopping containers..."
#            docker-compose down || { echo "docker-compose down failed"; exit 1; }
#
#            echo "Pulling latest images..."
#            docker-compose pull || { echo "docker-compose pull failed"; exit 1; }
#
#            echo "Rebuilding and restarting containers..."
#            docker-compose up -d --build || { echo "docker-compose up failed"; exit 1; }
#
#            echo "Docker Compose successfully restarted."
#          EOF

#      - name: Run database migrations
#        run: |
#          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
#            set -e
#            cd habits
#            echo "Running database migrations..."
#            docker-compose exec backend python manage.py migrate || { echo "Migrations failed"; exit 1; }
#          EOF

#      - name: Show Postgres logs if failed
#        if: failure()
#        run: |
#          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "docker logs postgres_data || true"

#      - name: Check running containers
#        run: |
#          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "docker ps"


#      - name: Deploy to Server
#        run: |
#          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
##          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/materials:${{ github.sha }}
#          cd ${{ secrets.DEPLOY_DIR }}
##          docker stop materials || true
#          git pull
#          docker-compose pull
##          docker rm materials || true
#          docker-compose down
##          docker run -d --name materials -p 80:8000 ${{ secrets.DOCKER_HUB_USERNAME }}/materials:${{ github.sha }}
#          docker-compose up -d --build
#          EOF
#
##      - name: Deploy to Server
##        run: |
##          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
##          cd ${{ secrets.DEPLOY_DIR }}
##          git pull
##          sudo docker-compose pull
##          sudo docker-compose down
##          sudo docker-compose up -d --build
###
##          EOF
